modLoader="javafml" #mandatory
loaderVersion="[28,)" #mandatory
[[mods]] #mandatory
modId="bettervanilla" #mandatory
version="1.0.1" #mandatory
logoFile="logo.png"
authors="Chokemonster" #optional
displayName="Better Vanilla" #mandatory
description='''
Adds tweaks that chokemonster needs to make vanilla fun
'''